# tasks/main.yml
---

# the package is needed to provide ipv4 address when gathering facts.
# ipv4 address is needed for the initial_cluster configuration

- name: install necessary packages
  ansible.builtin.apt:
    pkg:
      - iproute2
    state: latest
    update_cache: true

- name: collect facts
  ansible.builtin.setup:

    # - name: Display all variables/facts known for a host
    #ansible.builtin.debug:
    #var: ansible_facts
   
- name: Create {{ etcd_user }} system group
  ansible.builtin.group:
    name: "{{ etcd_user }}"
    state: present
    system: yes

- name: Create {{ etcd_group }} user
  ansible.builtin.user:
    name: "{{ etcd_group }}"
    groups: etcd
    append: yes
    shell: /sbin/nologin
    state: present
    system: yes

- name: Prepare directories
  ansible.builtin.file:
    state: directory
    path: "{{ item }}"
    owner: "{{ etcd_user }}"
    group: "{{ etcd_group }}"
    mode: '0750'
  loop:
    - /etc/etcd
    - "{{ etcd_data_dir }}"
  
- name: add configuration
  loop:
    - { f: etcd.conf.yaml, d: /etc/etcd }
  template:
    src: '{{ item.f }}.j2'
    dest: '{{ item.d }}/{{ item.f }}'
    owner: '{{ etcd_user }}'
    group: '{{ etcd_group }}'
    mode: 0644
      
- name: Copy systemd template
  ansible.builtin.template:
    src: etcd.service.j2
    dest: /etc/systemd/system/etcd.service
    owner: "{{ etcd_user }}"
    group: "{{ etcd_group }}"
    mode: 0644
  notify: restart etcd service
