name: "ansible-etcd-cluster: lint"

on:
  pull_request:
    branches:
      - 'main'

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
    - name: Set Up Git repository
      uses: actions/checkout@v3

    - name: Set Up Python 3.9
      uses: actions/setup-python@v2

    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

   # Check a machine's cgroup version
   # It shouldn't be "cgroup2fs"
    - name: Debug
      run: |
        env
        [[ $(stat -c %T -f /sys/fs/cgroup) != "cgroup2fs" ]]

    - name: Run lint
      run: |
        molecule lint

    # Will test every scenario with test_sequence from ../../molecule/default/molecule.yml
    - name: Run tests
      run: |
        molecule test --all
